---
- name: Deploy Docker container on target EC2
  hosts: targets
  become: yes

  tasks:
    - name: Install Docker (if not installed)
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Login to DockerHub
      shell: echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin

    - name: Pull Docker image
      shell: docker pull harshj2003/cicd-jenkins-ansible:latest

    - name: Stop and remove existing container (if running)
      shell: |
        docker ps -q --filter "name=myapp" | grep -q . && docker rm -f myapp || true

    - name: Run container
      shell: docker run -d --name myapp -p 80:5000 harshj2003/cicd-jenkins-ansible:latest

